### ISSUE TITLE
Failed to activate the faker package

### ISSUE THREAD

**Issue by gwaldvogel** [iorionda/faker#1]
Steps to reproduce:
1. Install the plugin
2. Exception is thrown

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.4
**Thrown From**: [faker](https://github.com/iori-o/faker) package, v0.1.0
### Stack Trace

Failed to activate the faker package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at createCommands (/Users/gwaldvogel/.atom/packages/faker/lib/faker.coffee:11:21)
    at /Users/gwaldvogel/.atom/packages/faker/lib/faker.coffee:8:9
    at Object.module.exports.activate (/Users/gwaldvogel/.atom/packages/faker/lib/faker.coffee:7:7)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
     -9:48 core:select-all (atom-text-editor.editor.mini.is-focused)
     -9:47.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -9:35.7.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -9:34.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -9:31.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -9:30.1.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -9:29.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -9:25.8.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  2x -9:25 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:03.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "task-list"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.20
aligner, v0.19.1
atom-autocomplete-php, v0.18.7
atom-jinja2, v0.5.0
auto-detect-indentation, v0.5.0
auto-indent, v0.5.0
autocomplete-clang, v0.8.9
autocomplete-cmake, v0.3.1
autocomplete-php, v0.3.7
autocomplete-sass, v0.1.0
autocomplete-wordpress-hooks, v0.2.0
build-cmake, v0.3.2
color-picker, v2.1.1
css-snippets, v0.9.0
faker, v0.1.0
file-icons, v1.6.18
git-diff-details, v0.23.0
git-log, v0.4.1
hyperclick-php, v0.2.1
imdone-atom, v1.3.27
indent-guide-improved, v1.4.5
language-apache, v1.4.0
language-blade, v0.20.0
language-cmake, v0.1.4
language-nginx, v0.6.1
language-puppet, v0.17.0
language-qml, v1.0.0
language-qtpro, v0.6.0
linter, v1.11.3
linter-php, v1.2.0
linter-puppet, v1.0.0
markdown-format, v2.5.1
minimap, v4.19.0
minimap-git-diff, v4.1.8
php-composer-completion, v0.3.4
php-cs-fixer, v2.5.6
php-debug, v0.2.2
php-integrator-annotations, v0.3.1
php-integrator-autocomplete-plus, v0.5.2
php-integrator-base, v0.6.9
php-integrator-call-tips, v0.2.1
php-integrator-navigation, v0.5.0
php-integrator-refactoring, v0.3.0
php-integrator-tooltips, v0.4.1
pigments, v0.25.0
project-manager, v2.7.6
react-snippets, v0.3.0
remote-edit, v1.8.24
travis-ci-status, v1.0.0
vagrant, v0.1.0
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by gwaldvogel** [comment]
Please see https://github.com/iorionda/faker/pull/2 for a solution.
